In [1]:
import glob
from tabulate import tabulate
from skimage import io
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import CoolProp.CoolProp as CP
from CoolProp.CoolProp import PropsSI
from CoolProp.Plots import PropertyPlot
from pyXSteam.XSteam import XSteam
steamTable = XSteam(XSteam.UNIT_SYSTEM_MKS)

In [2]:
Cosxkw_40 = 4489
Cosxkw_50 = 5051
Cosxkw_60  = 5416
Cosxkw_70 = 5376
Cosxkw_80 = 4953
Wnet40 = 32.593
Wnet50 = 20.598
Wnet60 = 15.754
Wnet70 = 13.196
Wnet80 = 11.657
TPPC40 = 146305820
TPPC50 = 104046945
TPPC60 = 85323072
TPPC70 = 70948129
TPPC80 = 57737777

In [ ]:
d140 = '-'
d240 = '-'
d340 = '-'
d440 = '-'
d540 = hex
d640 = pumps
d740 = tgt
d840 = wf
d940 = vess
d1040 = 0
d1140 = 0
d1240 = inst&con
d1340 = elect
d1440 = '-'
d1540 = 0
d1640 = 0
d1740 = sf
d1840 = '-'
d1940 = e&sup
d2040 = const
d2140 = conting
d2240 = '-'
d2340 = stup
d2440 = wcap
d2540 = cR&D
d2640 = sum(d540,d640,d740,d840,d940,d1240,d1340,d1740,d1940,d2040,d2140,d2340,d2440,d2540)
d2740 = d2640/(Wnet40)

In [ ]:
d140 = '-'
d240 = '-'
d340 = '-'
d440 = '-'
d540 = hex
d640 = pumps
d740 = tgt
d840 = wf
d940 = vess
d1040 = 0
d1140 = 0
d1240 = inst&con
d1340 = elect
d1440 = '-'
d1540 = 0
d1640 = 0
d1740 = sf
d1840 = '-'
d1940 = e&sup
d2040 = const
d2140 = conting
d2240 = '-'
d2340 = stup
d2440 = wcap
d2540 = cR&D
d2640 = sum(d540,d640,d740,d840,d940,d1240,d1340,d1740,d1940,d2040,d2140,d2340,d2440,d2540)
d2740 = d2640/(Wnet40)

In [ ]:
d140 = '-'
d240 = '-'
d340 = '-'
d440 = '-'
d540 = hex
d640 = pumps
d740 = tgt
d840 = wf
d940 = vess
d1040 = 0
d1140 = 0
d1240 = inst&con
d1340 = elect
d1440 = '-'
d1540 = 0
d1640 = 0
d1740 = sf
d1840 = '-'
d1940 = e&sup
d2040 = const
d2140 = conting
d2240 = '-'
d2340 = stup
d2440 = wcap
d2540 = cR&D
d2640 = sum(d540,d640,d740,d840,d940,d1240,d1340,d1740,d1940,d2040,d2140,d2340,d2440,d2540)
d2740 = d2640/(Wnet40)

In [ ]:
d140 = '-'
d240 = '-'
d340 = '-'
d440 = '-'
d540 = hex
d640 = pumps
d740 = tgt
d840 = wf
d940 = vess
d1040 = 0
d1140 = 0
d1240 = inst&con
d1340 = elect
d1440 = '-'
d1540 = 0
d1640 = 0
d1740 = sf
d1840 = '-'
d1940 = e&sup
d2040 = const
d2140 = conting
d2240 = '-'
d2340 = stup
d2440 = wcap
d2540 = cR&D
d2640 = sum(d540,d640,d740,d840,d940,d1240,d1340,d1740,d1940,d2040,d2140,d2340,d2440,d2540)
d2740 = d2640/(Wnet40)

In [ ]:
d140 = '-'
d240 = '-'
d340 = '-'
d440 = '-'
d540 = hex
d640 = pumps
d740 = tgt
d840 = wf
d940 = vess
d1040 = 0
d1140 = 0
d1240 = inst&con
d1340 = elect
d1440 = '-'
d1540 = 0
d1640 = 0
d1740 = sf
d1840 = '-'
d1940 = e&sup
d2040 = const
d2140 = conting
d2240 = '-'
d2340 = stup
d2440 = wcap
d2540 = cR&D
d2640 = sum(d540,d640,d740,d840,d940,d1240,d1340,d1740,d1940,d2040,d2140,d2340,d2440,d2540)
d2740 = d2640/(Wnet40)

In [9]:
row1 = ['FCI','A.Direct Cost','Onsite costs','PEC','HEX','Pumps','Turbine-Generator','Wf,tanks,pipes','Vesselmooring']
row2 = ['Inst','Instr&control','Electeq&mat','Offsite costs','Land','Civil','SF']
row3 = ['B.Indirect Cost','Eng&Sup','Const','Conting','OOutlays','StartUCost','WCapital','CLic&R&D','Total','TCI (USD/kW)']
rowtot = row1+row2+row3
k = ['32.593MW']
res40 = [d140, d240,d340,d440,d540,d640,d740,d840,d940,d1040,d1140,d1240,d1340,d1440,d1540,d1640,d1740,d1840,d1940,d2040,d2140,d2240,d2340,d2440,d2540,d2640,d2740]
res50 = 
res60 = 
res70 = 
res80 = 
dfCost = pd.DataFrame(row,columns=k,index=rowtot)
dfCost['20.598'] = (res50)
dfCost['15.754'] = (res60)
dfCost['13.196'] = (res70)
dfCost['11.657'] = (res80)
dfCost

                   32.593MW
FCI                       1
A.Direct Cost             2
Onsite costs              3
PEC                       4
HEX                       5
Pumps                     6
Turbine-Generator         7
Wf,tanks,pipes            8
Vesselmooring             9
Inst                      1
Instr&control             2
Electeq&mat               3
Offsite costs             4
Land                      5
Civil                     6
SF                        7
B.Indirect Cost           8
Eng&Sup                   9
Const                     1
Conting                   2
OOutlays                  3
StartUCost                4
WCapital                  5
CLic&R&D                  6
Total                     7
TCI (USD/kW)              8