In [2]:
import numpy as np
import pandas as pd
from numpy.linalg import inv

In [3]:
Variables = np.genfromtxt(fname='variables.txt')
COP = np.genfromtxt(fname='COP.txt')

In [27]:
Variables[0,1]

81.46

In [20]:
Variables[]

,0,1,2,3,4,5,6,7,8,9,...,6776,6777,6778,6779,6780,6781,6782,6783,6784,6785
0,81.35,81.46,81.66,81.82,82.10,82.28,82.45,82.63,82.77,83.25,...,87.60,87.66,87.70,87.64,87.75,87.73,87.61,87.75,87.64,87.70
1,75.02,75.84,76.13,76.14,76.15,76.02,75.81,76.42,76.37,76.74,...,81.81,81.72,81.73,81.74,81.73,81.76,81.76,81.73,81.74,81.67
2,85.32,86.66,86.39,86.31,86.52,86.50,86.96,88.03,86.92,87.73,...,93.87,93.96,93.94,94.02,94.02,94.08,94.13,94.23,94.35,94.32
3,83.16,83.13,82.96,83.08,83.06,83.06,83.04,83.14,83.14,83.21,...,87.96,87.89,88.04,87.93,87.90,87.95,87.93,88.02,88.06,87.93
4,81.35,81.46,81.66,81.82,82.10,82.28,82.45,82.63,82.77,83.25,...,87.60,87.66,87.70,87.64,87.75,87.73,87.61,87.75,87.64,87.70
5,77.03,77.09,77.16,77.29,77.40,77.49,77.55,77.66,77.75,78.02,...,81.27,81.27,81.24,81.25,81.27,81.25,81.26,81.28,81.28,81.28
6,41.79,41.86,41.89,41.98,42.05,42.10,42.16,42.22,42.26,42.42,...,56.34,56.31,56.28,56.26,56.23,56.20,56.16,56.14,56.13,56.09
7,28.67,28.68,28.69,28.72,28.76,28.76,28.79,28.79,28.80,28.83,...,33.22,33.23,33.23,33.23,33.23,33.24,33.22,33.23,33.22,33.23
8,68.62,70.47,72.03,74.75,75.29,74.24,71.36,67.16,72.47,75.97,...,34.58,35.75,34.83,34.74,34.71,34.67,36.11,35.09,34.89,34.86
9,75.02,75.84,76.13,76.14,76.15,76.02,75.81,76.42,76.37,76.74,...,81.81,81.72,81.73,81.74,81.73,81.76,81.76,81.73,81.74,81.67
10,52.39,52.39,52.39,52.39,52.39,52.39,52.39,52.39,52.39,52.39,...,55.25,55.25,55.25,55.25,55.25,55.25,55.25,55.25,55.25,55.25
11,51.08,51.08,51.08,51.08,51.08,51.08,51.08,51.08,51.08,51.08,...,54.33,54.33,54.33,54.33,54.33,54.33,54.33,54.33,54.33,54.33
12,51.08,51.08,51.08,51.08,51.08,51.08,51.08,51.08,51.08,51.08,...,54.33,54.33,54.33,54.33,54.33,54.33,54.33,54.33,54.33,54.33
13,53.49,53.49,53.49,53.49,53.49,53.49,53.49,53.49,53.49,53.49,...,55.97,55.97,55.97,55.97,55.97,55.97,55.97,55.97,55.97,55.97
14,10.00,10.00,10.00,10.00,10.00,10.00,10.00,10.00,10.00,10.00,...,9.00,9.00,9.00,9.00,9.00,9.00,9.00,9.00,9.00,9.00
15,20.00,20.00,20.00,20.00,20.00,20.00,20.00,20.00,20.00,20.00,...,21.10,21.10,21.10,21.10,21.10,21.10,21.10,21.10,21.10,21.10

In [4]:
TinGEAB = Variables[0,:]
TinEVAB = Variables[1,:] 
ToutABGE = Variables[2,:] 
TinABGE = Variables[3,:] 
ToutGECO = Variables[4,:] 
ToutGEAB = Variables[5,:] 
TinCO = Variables[6,:]
ToutCO = Variables[7,:] 
TinEV = Variables[8,:] 
ToutEVAB = Variables[9,:] 
XinAB = Variables[10,:]
XoutAB = Variables[11,:]
XinGE = Variables[12,:] 
XoutGE = Variables[13,:] 
PAB = Variables[14,:]
PGE = Variables[15,:]

In [5]:
TinGEAB_n =  TinGEAB/ 100.6830
TinEVAB_n =  TinEVAB / 98.9230
ToutABGE_n = ToutABGE / 108.0970
TinABGE_n = TinABGE / 101.8380
ToutGECO_n = ToutGECO / 100.6830
ToutGEAB_n =  ToutGEAB / 92.2790
TinCO_n = TinCO / 71.5550
ToutCO_n = ToutCO/ 37.1690
TinEV_n =  TinEV/ 93.8630
ToutEVAB_n = ToutEVAB / 98.9230
XinAB_n = XinAB / 60.8960
XoutAB_n =  XoutAB/ 59.7960
XinGE_n = XinGE / 59.7960
XoutGE_n =  XoutGE/ 61.6770
PAB_n =  PAB / 12.65
PGE_n = PGE / 23.21

In [6]:
P = [TinGEAB_n, TinEVAB_n, ToutABGE_n, TinABGE_n, ToutGECO_n, ToutGEAB_n, TinCO_n, ToutCO_n, TinEV_n, ToutEVAB_n, XinAB_n, XoutAB_n, XinGE_n, XoutGE_n, PAB_n, PGE_n]

In [7]:
V1 = np.transpose(Variables[0,:])
V2 = np.transpose(Variables[1,:])
V3 = np.transpose(Variables[2,:])
V4 = np.transpose(Variables[3,:])
V5 = np.transpose(Variables[4,:])
V6 = np.transpose(Variables[5,:])
V7 = np.transpose(Variables[6,:])
V8 = np.transpose(Variables[7,:])
V9 = np.transpose(Variables[8,:])
V10 = np.transpose(Variables[9,:])
V11 = np.transpose(Variables[10,:])
V12 = np.transpose(Variables[11,:])
V13 = np.transpose(Variables[12,:]) 
V14 = np.transpose(Variables[13,:])
V15 = np.transpose(Variables[14,:])
V16 = np.transpose(Variables[15,:])

In [8]:
V = [V1,V3/1000,V4/1000,V12/1000,(V12*V12)/1000,V15/1000,(V15**2)/1000,(V15**3)/1000, (V15**4)/1000, (V15**5)/1000, (V16)/1000, (V16**2)/1000, (V16**3)/1000]

In [9]:
unos = np.ones(np.size(np.transpose(Variables[1,:])))
unos
tCOP = np.transpose(COP)

In [308]:
Y = np.array([np.ones(len(V)), V]).T
a = inv(Y.T @ Y) @ Y.T @ subs

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  """Entry point for launching an IPython kernel.

UFuncTypeError: Cannot cast ufunc 'inv' input from dtype('O') to dtype('float64') with casting rule 'same_kind'

In [10]:
stot = []
x = [unos,V1,V3,V4,V12,(V12*V12)/1000,V15,(V15**2),(V15**3)/1000, (V15**4)/10000, (V15**5)/100000, (V16), (V16**2), (V16**3)/1000]
a1 = np.linalg.lstsq(np.transpose(x), (tCOP))
a = x/np.transpose(COP)
n1=np.size(Variables[1,:])
n2=len(a)
s=(np.zeros(np.size(Variables[1,:])))+(1.91232882e+04*(np.ones(np.size(Variables[1,:]))))/100000
for i in range(2,n2,1):
    s1 = (a[i]*np.transpose(x[i]))+s
    st = (s1 + s)
    stot.append(s1)
stot

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:3: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  This is separate from the ipykernel package so we can avoid doing imports until

[array([18665.58200211, 20297.36853018, 20171.08880045, ...,
        25369.5995186 , 25434.2555186 , 25418.08380431]),
 array([17732.46200211, 18677.4801518 , 18601.16853018, ...,
        22135.96380431, 22156.08723288, 22090.7195186 ]),
 array([6690.36148929, 7051.99231396, 7051.99231396, ..., 8433.7595186 ,
        8433.7595186 , 8433.7595186 ]),
 array([17.64700033, 18.59055532, 18.59055532, ..., 25.08500879,
        25.08500879, 25.08500879]),
 array([256.60148929, 270.46150315, 270.46150315, ..., 231.61980431,
        231.61980431, 231.61980431]),
 array([25641.21687391, 27027.21825991, 27027.21825991, ...,
        18745.9055186 , 18745.9055186 , 18745.9055186 ]),
 array([2.75533545, 2.89393558, 2.89393558, ..., 1.70963574, 1.70963574,
        1.70963574]),
 array([2.75533545, 2.89393558, 2.89393558, ..., 1.4211392 , 1.4211392 ,
        1.4211392 ]),
 array([2.75533545, 2.89393558, 2.89393558, ..., 1.187457  , 1.187457  ,
        1.187457  ]),
 array([1025.83225852, 1081.27231396, 1081.27231396, ..., 1272.21980431,
        1272.21980431, 1272.21980431]),
 array([410256.60148929, 432432.62366531, 432432.62366531, ...,
        566320.0315186 , 566320.0315186 , 566320.0315186 ]),
 array([164.29379698, 173.16420585, 173.16420585, ..., 252.32248898,
        252.32248898, 252.32248898])]

In [304]:
stot

[array([18665.58200211, 20297.36853018, 20171.08880045, ...,
        25369.5995186 , 25434.2555186 , 25418.08380431]),
 array([17732.46200211, 18677.4801518 , 18601.16853018, ...,
        22135.96380431, 22156.08723288, 22090.7195186 ]),
 array([6690.36148929, 7051.99231396, 7051.99231396, ..., 8433.7595186 ,
        8433.7595186 , 8433.7595186 ]),
 array([17.64700033, 18.59055532, 18.59055532, ..., 25.08500879,
        25.08500879, 25.08500879]),
 array([256.60148929, 270.46150315, 270.46150315, ..., 231.61980431,
        231.61980431, 231.61980431]),
 array([25641.21687391, 27027.21825991, 27027.21825991, ...,
        18745.9055186 , 18745.9055186 , 18745.9055186 ]),
 array([2.75533545, 2.89393558, 2.89393558, ..., 1.70963574, 1.70963574,
        1.70963574]),
 array([2.75533545, 2.89393558, 2.89393558, ..., 1.4211392 , 1.4211392 ,
        1.4211392 ]),
 array([2.75533545, 2.89393558, 2.89393558, ..., 1.187457  , 1.187457  ,
        1.187457  ]),
 array([1025.83225852, 1081.27231396, 1081.27231396, ..., 1272.21980431,
        1272.21980431, 1272.21980431]),
 array([410256.60148929, 432432.62366531, 432432.62366531, ...,
        566320.0315186 , 566320.0315186 , 566320.0315186 ]),
 array([164.29379698, 173.16420585, 173.16420585, ..., 252.32248898,
        252.32248898, 252.32248898])]

DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Requirement already satisfied: sklearn in /usr/local/lib/python3.7/site-packages (0.0)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.7/site-packages (from sklearn) (1.0.2)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/site-packages (from scikit-learn->sklearn) (1.1.0)
Requirement already satisfied: numpy>=1.14.6 in /usr/local/lib/python3.7/site-packages (from scikit-learn->sklearn) (1.21.5)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/site-packages (from scikit-learn->sklearn) (3.1.0)
Requirement already satisfied: scipy>=1.1.0 in /usr/local/lib/python3.7/site-packages (from scikit-learn->sklearn) (1.7.3)
Note: you may need to restart the kernel to use updated packages.

In [1]:
from sklearn.linear_model import LinearRegression

In [15]:
# Initialise and fit model
lm = LinearRegression()
model = lm.fit(np.transpose(V), tCOP)
model

LinearRegression()

In [12]:
pd.DataFrame(np.zeros(list(range(1, n1))))

ValueError: maximum supported dimension for an ndarray is 32, found 6785